ActorDec:A
KnownActor:A,a
VarDec:int,i
VarDec:boolean,odd
MsgHandlerDec:initial
VarDec:int,i2
Operator:=
Operator:=
MsgHandlerDec:foo
Conditional:if
Operator:==
Built-in:Print
Operator:+
Operator:*
Operator:=
Operator:!
Operator:=
Operator:++
MsgHandlerDec:bar
MsgHandlerCall:a,foo
ActorInstantiation:A,a1,a2
ActorInstantiation:A,a2,a1
